<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<ProjectReference Include="..\AFH.Location.Service.Application\AFH.Location.Service.Application.csproj" />
		<ProjectReference Include="..\AFH.Location.Service.Domain\AFH.Location.Service.Domain.csproj" />
		<ProjectReference Include="..\..\..\afh-sharepoint-integration\src\AFH.Common.SharePointUtils.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.ApplicationInsights" Version="2.23.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.9" />
		<PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.0" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="10.0.1" />
	</ItemGroup>

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

</Project>
