<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<ProjectReference Include="..\AFH.Location.Application\AFH.Location.Application.csproj" />
		<ProjectReference Include="..\AFH.Location.Domain\AFH.Location.Domain.csproj" />
		</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.ApplicationInsights" Version="3.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.5" />
		<PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.5" />
		<PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.5" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.5" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.5" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="10.0.5" />


		<PackageReference Include="AFH.Common.SharePointUtils" Version="2.0.1" />
		<PackageReference Include="AFH.Common.Errors.Email" Version="1.0.2"/>
		<PackageReference Include="AFH.Common.Errors.ApplicationInsights" Version="1.0.2" />
		<PackageReference Include="AFH.Common.Errors.EntityFramework" Version="1.0.2" />
		<PackageReference Include="Microsoft.Kiota.Abstractions" Version="1.22.2" />
		<PackageReference Include="OpenTelemetry.Api" Version="1.16.0" />


	</ItemGroup>

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

</Project>
