// <auto-generated />
using System;
using AFH.Location.Service.Infrastructure.Persistence.PolicyStore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AFH.Location.Service.Infrastructure.Persistence.PolicyStore.Migrations
{
    [DbContext(typeof(LocationPolicyDbContext))]
    [Migration("20260305133905_InitLocationPolicyStore")]
    partial class InitLocationPolicyStore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AFH.Location.Service.Infrastructure.Persistence.PolicyStore.Entities.AvailabilityDefaultPolicyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DefaultCompanyBufferMinutes")
                        .HasColumnType("int");

                    b.Property<int>("DefaultTravelBufferMinutes")
                        .HasColumnType("int");

                    b.Property<int>("MaxCompanyBufferMinutes")
                        .HasColumnType("int");

                    b.Property<int>("MaxTravelBufferMinutes")
                        .HasColumnType("int");

                    b.Property<int>("PreviousClientProximityMinutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AvailabilityDefaultPolicies", (string)null);
                });

            modelBuilder.Entity("AFH.Location.Service.Infrastructure.Persistence.PolicyStore.Entities.CoverageAdviserPolicyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdviserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaxTravelTimeMinutes")
                        .HasColumnType("int");

                    b.Property<double?>("RadiusMiles")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AdviserId")
                        .IsUnique();

                    b.ToTable("CoverageAdviserPolicies", (string)null);
                });

            modelBuilder.Entity("AFH.Location.Service.Infrastructure.Persistence.PolicyStore.Entities.CoverageDefaultPolicyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DefaultMaxTravelTimeMinutes")
                        .HasColumnType("int");

                    b.Property<double>("DefaultRadiusMiles")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("CoverageDefaultPolicies", (string)null);
                });

            modelBuilder.Entity("AFH.Location.Service.Infrastructure.Persistence.PolicyStore.Entities.CoverageRegionPolicyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("MaxTravelTimeMinutes")
                        .HasColumnType("int");

                    b.Property<double?>("RadiusMiles")
                        .HasColumnType("float");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Region")
                        .IsUnique();

                    b.ToTable("CoverageRegionPolicies", (string)null);
                });

            modelBuilder.Entity("AFH.Location.Service.Infrastructure.Persistence.PolicyStore.Entities.SearchAuditRecordEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CandidatesReturned")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DestinationPostcode")
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionsCsv")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("RequestedStartUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("SearchHorizonMinutes")
                        .HasColumnType("int");

                    b.Property<bool?>("SelectedAdviserGoldStar")
                        .HasColumnType("bit");

                    b.Property<string>("SelectedAdviserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("SelectedAdviserRating")
                        .HasColumnType("float");

                    b.Property<int?>("SelectedCompanyBufferMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("SelectedMaxTravelTimeMinutes")
                        .HasColumnType("int");

                    b.Property<string>("SelectedOriginSource")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("SelectedTravelBufferMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("SelectedTravelMinutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("RequestId");

                    b.ToTable("SearchAuditRecords", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
